import type { User } from "@/features/user-management/types";

export const mockUsers: User[] = [
  {
    id: "1",
    nickname: "닉네임입니다.",
    grade: "매니아",
    avatar: "/avatars/user1.svg",
    phone: "010-1234-1234",
    age: "1999년생",
    gender: "남자",
    region: "강남구",
    joinDate: "2022년 11월 1일",
    withdrawalDate: "2022년 11월 1일",
    role: "사용자",
    exerciseStyle: "보디빌딩",
    gymRelocation: "가능",
    bench: "100kg",
    deadlift: "100kg",
    squat: "100kg",
    intro: "한줄 소개 내용입니다.",
    profileImages: ["/profile/img1.svg", "/profile/img2.svg", "/profile/img3.svg"],
    settings: {
      profilePublic: false,
      matchChatNotification: true,
      marketingNotification: false,
    },
  },
  {
    id: "2",
    nickname: "닉네임입니다.",
    grade: "매니아",
    avatar: "/avatars/user2.svg",
    phone: "010-1234-1234",
    age: "1999년생",
    gender: "남자",
    region: "강남구",
    joinDate: "2022년 11월 1일",
    withdrawalDate: "2022년 11월 1일",
    role: "사용자",
    exerciseStyle: "보디빌딩",
    gymRelocation: "가능",
    bench: "100kg",
    deadlift: "100kg",
    squat: "100kg",
    intro: "한줄 소개 내용입니다.",
    profileImages: ["/profile/img1.svg", "/profile/img2.svg", "/profile/img3.svg"],
    settings: {
      profilePublic: false,
      matchChatNotification: true,
      marketingNotification: false,
    },
  },
  {
    id: "3",
    nickname: "닉네임입니다.",
    grade: "매니아",
    avatar: "/avatars/user3.svg",
    phone: "010-1234-1234",
    age: "1999년생",
    gender: "남자",
    region: "강남구",
    joinDate: "2022년 11월 1일",
    withdrawalDate: "2022년 11월 1일",
    role: "사용자",
    exerciseStyle: "보디빌딩",
    gymRelocation: "가능",
    bench: "100kg",
    deadlift: "100kg",
    squat: "100kg",
    intro: "한줄 소개 내용입니다.",
    profileImages: ["/profile/img1.svg", "/profile/img2.svg", "/profile/img3.svg"],
    settings: {
      profilePublic: false,
      matchChatNotification: true,
      marketingNotification: false,
    },
  },
  {
    id: "4",
    nickname: "닉네임입니다.",
    grade: "매니아",
    avatar: "/avatars/user4.svg",
    phone: "010-1234-1234",
    age: "1999년생",
    gender: "남자",
    region: "강남구",
    joinDate: "2022년 11월 1일",
    withdrawalDate: "2022년 11월 1일",
    role: "사용자",
    exerciseStyle: "보디빌딩",
    gymRelocation: "가능",
    bench: "100kg",
    deadlift: "100kg",
    squat: "100kg",
    intro: "한줄 소개 내용입니다.",
    profileImages: ["/profile/img1.svg", "/profile/img2.svg", "/profile/img3.svg"],
    settings: {
      profilePublic: false,
      matchChatNotification: true,
      marketingNotification: false,
    },
  },
  {
    id: "5",
    nickname: "닉네임입니다.",
    grade: "매니아",
    avatar: "/avatars/user5.svg",
    phone: "010-1234-1234",
    age: "1999년생",
    gender: "남자",
    region: "강남구",
    joinDate: "2022년 11월 1일",
    withdrawalDate: "2022년 11월 1일",
    role: "사용자",
    exerciseStyle: "보디빌딩",
    gymRelocation: "가능",
    bench: "100kg",
    deadlift: "100kg",
    squat: "100kg",
    intro: "한줄 소개 내용입니다.",
    profileImages: ["/profile/img1.svg", "/profile/img2.svg", "/profile/img3.svg"],
    settings: {
      profilePublic: false,
      matchChatNotification: true,
      marketingNotification: false,
    },
  },
];

export const totalUserCount = 100000;
